:new_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/newapplications/xml
:top_free_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/topfreeapplications/limit=100/genre=6014/xml
:top_paid_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/toppaidapplications/limit=100/genre=6014/xml
:top_grossing_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/topgrossingapplications/limit=100/genre=6014/xml
:top_free_ipad_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/topfreeipadapplications/limit=100/genre=6014/xml
:top_paid_ipad_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/toppaidipadapplications/limit=100/genre=6014/xml
:top_grossing_ipad_applications: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/topgrossingipadapplications/limit=100/genre=6014/xml
